BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `tutoriales` (
	`id_tutorial`	INTEGER NOT NULL DEFAULT 0 PRIMARY KEY AUTOINCREMENT UNIQUE,
	`sistema`	VARCHAR NOT NULL,
	`nombre`	VARCHAR NOT NULL,
	`terminado`	BOOL NOT NULL DEFAULT 0
);
COMMIT;
